wallpaper {
    monitor = HDMI-A-1
    path = /home/anders/.config/hypr/wallpapers/lucas-k-R79qkPYvrcM-unsplash.jpg
}

wallpaper {
    monitor = eDP-1
    path = ~/.config/hypr/wallpapers/lucas-k-R79qkPYvrcM-unsplash.jpg
}

wallpaper {
    monitor = DP-4
    path = ~/.config/hypr/wallpapers/lucas-k-R79qkPYvrcM-unsplash.jpg
}
